# Generated by Django 3.2 on 2021-05-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fresher', '0003_auto_20210527_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
