# Generated by Django 3.2 on 2021-05-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fresher', '0004_auto_20210527_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipes',
            new_name='Recipe',
        ),
    ]
