# Generated by Django 3.2 on 2021-05-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fresher', '0005_rename_recipes_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Recipes',
        ),
    ]
